openapi: 3.0.1
info:
  title: Companies API
  description: This is the Companies API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.3.0
paths:
  /:
    get:
      summary: Returns available resources
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Root'
  /companies:
    get:
      summary: Gets a list of companies
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Companies'
  /companies/{companyId}:
    get:
      summary: Gets data about a single company
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        '400':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Unsuccessful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'  
components:
  schemas:
    Root:
      type: object
    Companies:
      type: array
      items:
        type: object
    Company:
      type: object
      properties:
        id:
          type: string
        name: 
          type: string
        summary:
          type: string
        careers:
          type: string
    Error:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
        url:
          type: string
      