language: node_js
node_js:
  - '14'
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: kVGVQd33rV0YU5n+O8gwf5uGk6cVCFo+gAo7f+6MjQc+f44CTHSO4DuxB/RBbR0XpOgsZ8onvCSyDX/CibrMq1kGre9C1bcaIbKBcnKB6MC4spNW96g9Gxr4aq4E3rFQ0NjYtQu1+yoVjHkmVmZsJhrJIcVt87rqe/PPC2iKdMPUVIYaEjdh4Ww3jQSZmWT0eiSY8rMFcjj4JHueAHhFsvmi5of48OWJib5ZC0Q00nGuCTmEAHS/+E3dLHWwigevH912obhohJqxXCYVtlCHLAwHDsJw4R5mWzdOz5LAUA4hz9NYh+K55slUk3X9TwlGpid+f5Zwzd43sF+CBjl1c1b9BiaZEb3NKbO7OuM/to2NcYFdiLSDa3mEDGJP1lJmOnEHmBPSocBFmwPK/A7IpsJuvI1haIYrSLyaR53Exw8Pq2ivz+VLjCDcm75KmLLT2YOoRjdkP2QOcrxmlCW18gBCuyJEz7Hp31ThnLbi/YyUOXvTBCWXqKT7+JtNv6RqUrAIo+917rzDlHqGYhQA314KIEiIp5GZcJ/qOzXJM09lVLN9RsfmaEqGhXVgrRJdlMr/UEEUsLxpGoKHEoo9kb2YddU/o57wl6KWgpqf0Ib2XHmqZQQZ1QcwW7VTJrsuXyE68caeC+gNP31nOQmbXfMc6efVhEBKZpr9wjsrfqQ=
  on:
    branch: main
    